### ISSUE TITLE
Vessel IDs for follow up of vessels?

### ISSUE THREAD

**Issue by yvonneyangyy** [RUB-Bioinf/VesselExpress#9]
Dear developers,

Thank you so much for the very helpful tool. Can you, by any chance, find the vessel IDs of every vessel with output from the skeletonization to follow up on changes in every vessel branch? We are analyzing our intravital imaging data with stacks of the same region using your tool, but we would really love to understand how each vessel changes over time.

Our alternative approach is to crop out each vessel from the ROI and feed it to VesselExpress, but this is quite time-consuming.

Thanks for your help,

Yvonne Yang

**Comment by jxchen01** [comment]
Thanks for your interest. Just to make sure i understand your question correctly: you want to follow the vessels one after another? E.g., the vessel branch from node 1 to node 2, then the vessel branch from node 2 to node X, then the vessel branch from node X to node Y, etc. correct? More like you want to analyze a specific path on the graph, instead of individual vertice and edges, correct?

Jianxu

**Comment by yvonneyangyy** [comment]
Hi Jianxu,

thank you so much for your fast reply.
I have taken the image of the same ROI over time. So I have a hyperstack with xyzt. Since the stacks are registered onto each other, I can identify by eye, which vessel is which in the next time point. I do not need to follow up the hierachy of the vessels and their branches but compare every branch to the exact same branch in the time point later. Therefore I would need to analyze specific individual paths and map it to recombine the data with the next time point.  As an output of VesselExpress, there is a filament ID. Are these given randomly or according to coordinates? 

Thank you so much for your help and best regards,

Yvonne

**Comment by philippa1812** [comment]
Hi @yvonneyangyy,

the filament IDs are given randomly but the segment IDs in the Segment_Statistics.csv file are given according to the start and end point of each vessel as such: ((startpoint_z, startpoint_y, startpoint_x), (endpoint_z, endpoint_y, endpoint_x)) and are mapped to the filament IDs. That way you can see exactly which vessels/segments belong to a filament ID.

Best 
Philippa

**Comment by yvonneyangyy** [comment]
Hi @philippa1812,

thank you so much for the notification! This could be a solution for our problem. 

Best,

Yvonne
